language: julia
os:
  - linux
  - osx
julia:
  # - release
  - nightly
notifications:
  email: false
script:
  - if [ -e .git/shallow ]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Hwloc")'
  - julia -e 'Pkg.test("Hwloc")'
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'Pkg.add("Coverage"); using Coverage; cd(Pkg.dir("Hwloc")); Coveralls.submit(Coveralls.process_folder())'; fi
