language: julia
os:
  - linux
  - osx
julia:
  - release
  - 0.4
  - nightly
notifications:
  email: false
script:
  - if [ -e .git/shallow ]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Hwloc")'
  - if [ "$TRAVIS_JULIA_VERSION" = nightly ]; then julia -e 'Pkg.test("Hwloc", coverage=true)'; else julia -e 'Pkg.test("Hwloc")'; fi
after_success:
  - if [ "$TRAVIS_JULIA_VERSION" = nightly ]; then julia -e 'cd(Pkg.dir("Hwloc")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
