name = "Hwloc"
uuid = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "1.0.3"

[deps]
Hwloc_jll = "e33a78d0-f292-5ffc-b300-72abe9b543c8"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
